//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int clientId { get; set; }
        public string FirstName { get; set; }
        public string secondName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public int Fascility_Id { get; set; }
        public string Address { get; set; }
        public int youthGroupTypeId { get; set; }
        public int districtsId { get; set; }
    
        public virtual district district { get; set; }
        public virtual Fascility Fascility { get; set; }
        public virtual YouthGroup YouthGroup { get; set; }
    }
}
