//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complaint
    {
        public int complaintId { get; set; }
        public int districtsId { get; set; }
        public string complaintBy { get; set; }
        public System.DateTime dateOfComplaint { get; set; }
        public bool isSolved { get; set; }
        public string complaintDescription { get; set; }
        public int isDeleted { get; set; }
    
        public virtual district district { get; set; }
    }
}
