//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fascility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fascility()
        {
            this.Clients = new HashSet<Client>();
        }

        public int Fascility_Id { get; set; }
        public string Fascility_Name { get; set; }
        public string Fascility_Description { get; set; }
        public string WasteCollectionPricePerMonth { get; set; }
        public string districtName { get; set; }
        public int isDeleted { get; set; }
        public int districtsId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        public virtual district district { get; set; }
    }
}
