//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fascility
    {
        public int Fascility_Id { get; set; }
        public string Fascility_Name { get; set; }
        public string Fascility_Description { get; set; }
        public string WasteCollectionPricePerMonth { get; set; }
        public int isDeleted { get; set; }
    }
}
