//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicWasteBin
    {
        public int publicWasteBinId { get; set; }
        public string publicWasteBinName { get; set; }
        public string publicWasteBinDescription { get; set; }
        public int collectionSiteId { get; set; }
        public int isDeleted { get; set; }
        public string publicWasteBinNumber { get; set; }
        public string publicWasteBinSiteManager { get; set; }
        public string siteName { get; set; }
        public virtual collectionSite collectionSite { get; set; }
    }
}
