//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.Staff_Task = new HashSet<Staff_Task>();
        }
    
        public int staffId { get; set; }
        public int districtsId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userDisplayName { get; set; }
        public string email { get; set; }
        public string passwordsalt { get; set; }
        public string password { get; set; }
        public System.DateTime dateOfAccountCreation { get; set; }
        public int isDeleted { get; set; }
    
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Task> Staff_Task { get; set; }
    }
}
