//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Task
    {
        public int task_id { get; set; }
        public int staff_id { get; set; }
        public int task_name { get; set; }
        public System.DateTime task_start_date { get; set; }
        public System.DateTime task_end_date { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
