//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ward()
        {
            this.sections = new HashSet<section>();
        }
    
        public int wardId { get; set; }
        public int constituenciesId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int isDeleted { get; set; }
    
        public virtual constituency constituency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<section> sections { get; set; }
    }
}
