//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wwmDbEntities : DbContext
    {
        public wwmDbEntities()
            : base("name=wwmDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<collectionSite> collectionSites { get; set; }
        public virtual DbSet<community> communities { get; set; }
        public virtual DbSet<complaint> complaints { get; set; }
        public virtual DbSet<constituency> constituencies { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<districtAdmin> districtAdmins { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<Fascility> Fascilities { get; set; }
        public virtual DbSet<publicWasteBin> publicWasteBins { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<Staff_Task> Staff_Task { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ward> wards { get; set; }
        public virtual DbSet<YouthGroup> YouthGroups { get; set; }
        public virtual DbSet<YouthGroupAdmin> YouthGroupAdmins { get; set; }
    }
}
