//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouthGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YouthGroup()
        {
            this.YouthGroupAdmins = new HashSet<YouthGroupAdmin>();
        }
    
        public int youthGroupTypeId { get; set; }
        public string youthGroupName { get; set; }
        public string youthGroupDescription { get; set; }
        public int districtsId { get; set; }
        public string districtName { get; set; }
        public int isDeleted { get; set; }
    
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YouthGroupAdmin> YouthGroupAdmins { get; set; }
    }
}
