//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouthGroupAdmin
    {
        public int YouthGroupAdminId { get; set; }
        public string YouthGroupAdminName { get; set; }
        public string YouthGroupAdminDescription { get; set; }
        public int isDeleted { get; set; }
        public string UserId { get; set; }
        public int youthGroupTypeId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual YouthGroup YouthGroup { get; set; }
    }
}
