//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class youthGroup
    {
        public int youthGroupId { get; set; }
        public int districsId { get; set; }
        public string youthGroupName { get; set; }
        public string youthGroupDescription { get; set; }
        public bool isApproved { get; set; }
        public string address { get; set; }
        public string UserId { get; set; }
        public int isDeleted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
